### ISSUE TITLE
Unclear how to link against this project

### ISSUE THREAD

**Issue by adorokhine** [Simplx-dev/kotlin-format#1]
I can't figure out how to use this project. There's no gradle coords on the readme, no documented dependency path, and I couldn't find anything searching mvnrepository.com for kotlin-format or for simplx. Please document! I want to start using it :)

**Comment by bohdanbezp** [comment]
Added the library to jitpack repository.

Usage
```gradle
dependencies {
      implementation 'com.github.Simplx-dev:kotlin-format:1.2
}
```
